services:
  web:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"

  app:
    build:
      context: ./backend
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - "3306:3306"
    container_name: mysql
